# Generated by Django 3.2 on 2023-09-30 05:44

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to=media.models.gallery_image_file_path),
        ),
    ]
